/**
 * Split 07 — T1: `map.js` mapper fidelity + the engine↔UI parity invariant.
 *
 * Drives `ChartExtractMap` against canned `ExtractionResult` fixtures (the real Split 06 stub
 * responses, generated by `_gen_fixtures.py`) and asserts every view-model field the existing
 * component binds to is produced correctly: the §5 nulls (`margin_status`→not_assessed cites its
 * span, `lymph_nodes_positive`→not_found), the intake `ListField` flattening + `pcp`→not_found,
 * footer counts, the JSON body, and the eval view. The parity test confirms the engine's
 * flags/confidence equal the UI's reference JS `grounded()` on the same text — the cross-stack
 * "engine and UI agree" guarantee from `00-PROGRESS.md`.
 */
"use strict";

const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const Map = require("../map.js");

const FX = path.join(__dirname, "fixtures");
function fixture(name) {
  return JSON.parse(fs.readFileSync(path.join(FX, name), "utf8"));
}

const pathResult = fixture("extract_path.json");
const pathCaughtResult = fixture("extract_path_caught.json");
const intakeResult = fixture("extract_intake.json");
const samples = fixture("samples.json");
const evalReport = fixture("eval.json");

function byName(rows) {
  return Object.fromEntries(rows.map((r) => [r.name, r]));
}

// --- toFieldRows: pathology -------------------------------------------------

test("toFieldRows(path): names/values/flags/offsets carried from the result", () => {
  const rows = Map.toFieldRows(pathResult);
  assert.equal(rows.length, 9);
  assert.deepEqual(
    rows.map((r) => r.name),
    [
      "specimen",
      "diagnosis",
      "grade",
      "tumor_size_cm",
      "er_status",
      "pr_status",
      "her2_status",
      "margin_status",
      "lymph_nodes_positive",
    ]
  );
  const m = byName(rows);

  // a clean accepted field: value, flag→'accepted', offsets + confidence straight from the API.
  assert.equal(m.tumor_size_cm.value, 1.4);
  assert.equal(m.tumor_size_cm.flag, "accepted");
  assert.equal(m.tumor_size_cm.conf, 0.95);
  assert.equal(m.tumor_size_cm.s, 252);
  assert.equal(m.tumor_size_cm.e, 269);
  assert.equal(m.tumor_size_cm.q, "exact");

  // the two distinct nulls (the headline of the whole demo).
  assert.equal(m.margin_status.value, null);
  assert.equal(m.margin_status.flag, "not_assessed");
  assert.equal(m.margin_status.span, "Margins not assessed on this specimen"); // detail cites this
  assert.equal(m.lymph_nodes_positive.value, null);
  assert.equal(m.lymph_nodes_positive.flag, "not_found");
  assert.equal(m.lymph_nodes_positive.span, "");
});

test("toFieldRows: the engine's null flag becomes the literal 'accepted' the FLAGS table keys on", () => {
  const m = byName(Map.toFieldRows(pathResult));
  // specimen has flag:null in the result; the component's FLAGS lookup needs 'accepted'.
  assert.equal(pathResult.fields[0].flag, null);
  assert.equal(m.specimen.flag, "accepted");
});

test("toFieldRows(path, caught): not_grounded carries model_value through as `proposed`", () => {
  const m = byName(Map.toFieldRows(pathCaughtResult));
  const lnp = m.lymph_nodes_positive;
  assert.equal(lnp.flag, "not_grounded");
  assert.equal(lnp.value, null); // engine nulled the ungrounded value
  assert.equal(lnp.proposed, 2); // ...but kept what the model said
  assert.equal(lnp.model_value, 2);
  assert.equal(lnp.s, null); // no offsets for an ungrounded span
});

// --- toFieldRows: intake (ListField) ----------------------------------------

test("toFieldRows(intake): ListField flattened to name[i]; pcp→not_found", () => {
  const rows = Map.toFieldRows(intakeResult);
  assert.deepEqual(
    rows.map((r) => r.name),
    [
      "patient_name",
      "dob",
      "sex",
      "chief_complaint",
      "medications[0]",
      "medications[1]",
      "medications[2]",
      "allergies[0]",
      "pcp",
    ]
  );
  const m = byName(rows);
  assert.equal(m["medications[0]"].value, "Lisinopril 10 mg daily");
  assert.equal(m["medications[2]"].value, "Atorvastatin 20 mg nightly");
  assert.equal(m.chief_complaint.flag, "needs_review"); // low model confidence (0.55)
  assert.equal(m.pcp.value, null);
  assert.equal(m.pcp.flag, "not_found");
});

// --- toHighlightRanges: offsets verbatim, NOT re-grounded -------------------

test("toHighlightRanges uses the API char_start/char_end verbatim", () => {
  const ranges = Map.toHighlightRanges(pathResult);
  const m = byName(ranges);
  // 8 located fields produce ranges: the 7 present fields + `margin_status` (not_assessed keeps its
  // cited-absence offsets so the cyan wash works — Split 08). Only `not_found` has null offsets.
  assert.equal(ranges.length, 8);
  assert.equal(m.specimen.s, 179);
  assert.equal(m.specimen.e, 202);
  assert.equal(m.tumor_size_cm.s, 252);
  assert.equal(m.tumor_size_cm.e, 269);
  assert.ok("margin_status" in m); // not_assessed → cited-absence offsets → a (cyan) range
  assert.ok(!("lymph_nodes_positive" in m)); // not_found → no value, no offsets, no range
});

test("toHighlightRanges does NOT re-run grounding: it trusts offsets JS ground() would disagree with", () => {
  // Feed a result whose char offsets deliberately do NOT match where the text actually is. A mapper
  // that re-grounded would "fix" them; ours must echo the API's numbers exactly.
  const doctored = {
    fields: [
      { name: "specimen", value: "x", source_span: "Left breast core biopsy", char_start: 5, char_end: 9, match_quality: "exact", confidence: 0.9, flag: null },
    ],
  };
  const ranges = Map.toHighlightRanges(doctored);
  assert.equal(ranges.length, 1);
  assert.equal(ranges[0].s, 5); // the (wrong-on-purpose) API offset wins — proof we never re-ground
  assert.equal(ranges[0].e, 9);
});

// --- footer / json ----------------------------------------------------------

test("toFooterCounts(path): counts text + chips match the existing footer bindings", () => {
  const f = Map.toFooterCounts(pathResult);
  assert.equal(f.countsText, "7 grounded · 2 null (1 not_found · 1 not_assessed)");
  assert.match(f.cost, /^\$\d+\.\d{3}$/);
  assert.match(f.latency, /^\d+\.\ds$/);
  assert.equal(f.pv, "prompt v3");
  assert.equal(f.sv, "schema v2");
  assert.equal(f.model, "claude-opus-4-8");
});

test("toFooterCounts(intake): null + review reflected", () => {
  const f = Map.toFooterCounts(intakeResult);
  assert.equal(f.countsText, "8 grounded · 1 null (1 not_found · 0 not_assessed) · 1 review");
});

test("toFooterCounts(caught): not_grounded surfaced in the counts", () => {
  const f = Map.toFooterCounts(pathCaughtResult);
  // caught variant: lymph_nodes_positive → not_grounded (still a null).
  assert.match(f.countsText, /not_grounded/);
});

// --- cost tooltip token breakdown (Split 11, UIUX §5.4) ---------------------

test("toFooterCounts(path): cost tooltip carries the engine token breakdown", () => {
  const f = Map.toFooterCounts(pathResult);
  assert.equal(f.tokens.input, 1200);
  assert.equal(f.tokens.output, 180);
  assert.equal(f.tokens.cache, 0); // sub-floor demo doc → honest cache miss
  assert.equal(f.tokens.text, "input 1200 · output 180 · cache-read 0");
});

test("toCostBreakdown: surfaces a non-zero cache-read when the prefix cached", () => {
  const cached = { input_tokens: 904, output_tokens: 180, cache_read_tokens: 4096 };
  const b = Map.toCostBreakdown(cached);
  assert.equal(b.input, 904);
  assert.equal(b.cache, 4096);
  assert.equal(b.text, "input 904 · output 180 · cache-read 4096");
});

test("toCostBreakdown: missing token fields read as 0 (never NaN)", () => {
  const b = Map.toCostBreakdown({});
  assert.equal(b.input, 0);
  assert.equal(b.output, 0);
  assert.equal(b.cache, 0);
  assert.equal(b.text, "input 0 · output 0 · cache-read 0");
});

test("toEvalView: cost rows carry the measured-vs-estimated label (Split 11)", () => {
  const v = Map.toEvalView(evalReport);
  assert.ok(v.cost.length >= 2);
  // The frozen-stub artifact's Anthropic rows are estimates, never presented as measured.
  for (const c of v.cost) {
    assert.equal(c.measured, false);
    assert.equal(c.basis, "estimate");
  }
  // A measured row (live sweep) labels itself accordingly.
  const live = Map.toEvalView({
    cost: [{ model: "gpt-5.5", f1: 0.87, usd_per_doc: 0.0056, measured: true }],
  });
  assert.equal(live.cost[0].measured, true);
  assert.equal(live.cost[0].basis, "measured");
});

test("toJsonText: the raw ExtractionResult with real offsets, round-trips", () => {
  const txt = Map.toJsonText(pathResult);
  const parsed = JSON.parse(txt);
  assert.deepEqual(parsed, pathResult);
  assert.equal(parsed.fields[3].char_start, 252); // a real offset is present in the inspector body
});

// --- eval view --------------------------------------------------------------

test("toEvalView: macro-F1 / halluc 0 / routing / rows from /api/eval", () => {
  const v = Map.toEvalView(evalReport);
  assert.equal(v.macroF1, "1.00");
  assert.equal(v.halluc, "0"); // exactly-zero reads as the bare headline
  assert.equal(v.routing, "1.00");
  assert.equal(v.goldCount, 15);
  assert.equal(v.evalRows.length, evalReport.rows.length);
  const first = v.evalRows[0];
  assert.equal(first.name, "specimen");
  assert.equal(first.f1, "1.00");
  assert.equal(first.w, "100%");
});

// --- purity / totality ------------------------------------------------------

test("mapper is pure: deterministic + does not mutate input", () => {
  const input = fixture("extract_path.json");
  const before = JSON.stringify(input);
  assert.deepEqual(Map.toFieldRows(input), Map.toFieldRows(input));
  assert.equal(JSON.stringify(input), before);
});

test("mapper is total: empty/partial input never throws", () => {
  assert.doesNotThrow(() => Map.toFieldRows({}));
  assert.doesNotThrow(() => Map.toFieldRows(undefined));
  assert.doesNotThrow(() => Map.toHighlightRanges(undefined));
  assert.doesNotThrow(() => Map.toFooterCounts(undefined));
  assert.doesNotThrow(() => Map.toEvalView(undefined));
  assert.deepEqual(Map.toFieldRows({}), []);
  assert.deepEqual(Map.toHighlightRanges({}), []);
});

test("samples fixture matches the canonical example text the document pane indexes into", () => {
  const path0 = samples.find((s) => s.id === "path_report");
  // the API offset for specimen (179..202) must slice the sample text to the exact span.
  assert.equal(path0.text.slice(179, 202), "Left breast core biopsy");
});

// --- T1 parity: engine flags/confidence == reference JS grounded() ----------
//
// A verbatim copy of the component's reference `ground()/grounded()/TEXT/pathDefs()` (which live in
// the `<script type="text/x-dc">` Component inside ChartExtract.dc.html). The documented cross-stack
// invariant is that the Python engine produces byte-identical flags/confidence for the same inputs,
// so the live API body must equal what this reference computes on the same text.

const REF_TEXT = `SURGICAL PATHOLOGY REPORT
Accession No: SP-26-04417        Reported: 2026-06-22

CLINICAL HISTORY: 54-year-old female, palpable mass,
left breast upper outer quadrant.

SPECIMEN: Left breast core biopsy.

DIAGNOSIS:
Invasive ductal carcinoma, grade 2.
Tumor size 1.4 cm. ER positive (90%), PR positive (40%),
HER2 negative.

COMMENT: Margins not assessed on this specimen.
Correlation with imaging is recommended.`;

function refPathDefs() {
  return [
    { name: "specimen", value: "Left breast core biopsy", span: "Left breast core biopsy", mc: 0.96 },
    { name: "diagnosis", value: "Invasive ductal carcinoma", span: "Invasive ductal carcinoma, grade 2", mc: 0.93 },
    { name: "grade", value: "2", span: "grade 2", mc: 0.9 },
    { name: "tumor_size_cm", value: "1.4 cm", span: "Tumor size 1.4 cm", mc: 0.95 },
    { name: "er_status", value: "positive", span: "ER positive (90%)", mc: 0.94 },
    { name: "pr_status", value: "positive", span: "PR positive (40%)", mc: 0.92 },
    { name: "her2_status", value: "negative", span: "HER2 negative", mc: 0.93 },
    { name: "margin_status", value: null, span: "Margins not assessed on this specimen", mc: 0 },
    { name: "lymph_nodes_positive", value: null, span: "", mc: 0 },
  ];
}

function refGround(span, text) {
  if (!span) return { q: "none", s: null, e: null, count: 0 };
  const i = text.indexOf(span);
  if (i !== -1) {
    const count = text.split(span).length - 1;
    return { q: "exact", s: i, e: i + span.length, count };
  }
  const esc = (x) => x.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const toks = span.trim().split(/\s+/).map(esc);
  try {
    const re = new RegExp(toks.join("\\s+"));
    const m = re.exec(text);
    if (m) return { q: "whitespace", s: m.index, e: m.index + m[0].length, count: 1 };
  } catch (e) {}
  const pre = span.replace(/\s+/g, " ").slice(0, 40);
  const j = text.indexOf(pre);
  if (j !== -1) return { q: "prefix", s: j, e: j + pre.length, count: 1 };
  return { q: "none", s: null, e: null, count: 0 };
}

function refGrounded() {
  const text = REF_TEXT,
    tau = 0.6;
  return refPathDefs().map((f) => {
    const g = refGround(f.span, text);
    let flag,
      value = f.value,
      conf = 0;
    if (value != null) {
      if (g.q === "none") {
        flag = "not_grounded";
        value = null;
        conf = 0;
      } else {
        const w = { exact: 1, whitespace: 0.92, prefix: 0.5 }[g.q];
        conf = Math.min(f.mc, w);
        if (g.count > 1 && f.span.replace(/\s/g, "").length < 12) flag = "ambiguous_span";
        else if (conf < tau || g.q === "prefix") flag = "needs_review";
        else flag = "accepted";
      }
    } else {
      if (!f.span) flag = "not_found";
      else if (g.q !== "none") flag = "not_assessed";
      else flag = "not_found";
    }
    return { name: f.name, flag, conf: Number(conf.toFixed(2)) };
  });
}

test("PARITY: engine API flags/confidence == reference JS grounded() on the same path text", () => {
  const ref = byName(refGrounded());
  const api = byName(
    pathResult.fields.map((f) => ({
      name: f.name,
      flag: f.flag || "accepted",
      conf: Number((f.confidence || 0).toFixed(2)),
    }))
  );
  for (const name of Object.keys(ref)) {
    assert.equal(api[name].flag, ref[name].flag, `flag mismatch for ${name}`);
    assert.equal(api[name].conf, ref[name].conf, `confidence mismatch for ${name}`);
  }
});
